#!/usr/bin/env bash
version='3.1.2'
data=
link='nolink'
ofname='qr'
size='auto'
level='M'
pad='tight'
nruns=2

echoCopyright() {
    echo '
Copyright (c) 2026 Yavuz Köroğlu
'
}

echoUsage() {
    echo "
qrcreate, v${version}
Copyright (c) 2026 Yavuz Köroğlu

Usage: qrcreate <OPTIONS>

OPTIONS:
  -c, --copyright                   Output the copyright message and exit.
  -d, --data-str <STRING>           Set the data to be encoded to <STRING>.
  -h, --help                        Output this help message and exit.
  -i, --input-filename <FILENAME>   Load data to be encoded from <FILENAME>.
  -l, --link                        Make the generated QR code clickable (default: nolink).
  -L, --level L|M|Q|H               Set error correction level ('Low', default: 'Medium', 'Quality', or 'High').
  -n, --nolink                      Make the generated QR code unclickable (default: nolink).
  -N, --nruns <NUMBER>              Specify the number of re-compilations (default: 2).
  -o, --output-filename <FILENAME>  Set the output filename without the .pdf extension (default: qr).
  -p, --padding                     Set padding around the QR code to non-zero (default: tight).
  -t, --tight                       Set padding around the QR code to zero (default: tight).
  -s, --stdin                       Load data to be encoded from standard input.
  -S, --size <NUMBER>|auto          Set the QR size (default: auto, otherwise a value btw. 1-40).
  -v, --version                     Output the version information and exit.

OUTPUT:
  A PDF file containing a QR code of the given data.

EXAMPLE USES:
  qrcreate -d "https://web.itu.edu.tr/yakoroglu" -l -p -o myqr.pdf
  qrcreate -d 'https://' -s -d '/yakoroglu' -l -p -o myqr.pdf <<< 'web.itu.edu.tr'
  qrcreate -d 'https://' -i "example.txt" -s -l -p -o myqr.pdf <<< '/yakoroglu'

NOTE:
  => Multiple data sources will be concatenated in the given order.
  => LaTeX special characters may not be processed correctly. See qrcodetikz CTAN package for details.
"
}

echoVersion() {
    echo "${version}"
}

processDataStr() {
    case "${1}" in
        '')
            echo "ERROR: No data given after -d or --data-str" >&2
            exit 1;
            ;;
        *)
            data="${data}${1}"
            ;;
    esac
}

processInputFile() {
    case "${1}" in
        -*|'')
            echo "ERROR: No FILENAME given after -i or --input-filename." >&2
            exit 1
            ;;
        *)
            if [[ -f "${1}" ]]
            then
                data+=$(<"${1}")
            else
                echo "ERROR: No such file -- '${1}'." >&2
                exit 1
            fi
            ;;
    esac
}

processLevel() {
    case "${1}" in
        L|M|Q|H)
            level=${1}
            ;;
        *)
            echo "ERROR: Unknown level ${1}, it must be L, M, Q, or H." >&2
            exit 1
            ;;
    esac
}

processNRuns() {
    case "${1}" in
        ''|*[!0-9]*)
            echo "ERROR: Missing valid NUMBER after -n or --nruns." >&2
            exit 1
            ;;
        *)
            nruns="${1}"
            ;;
    esac
    if (( ${nruns} < 1 ))
    then
        echo "ERROR: The NUMBER after -n must be greater than zero." >&2
        exit 1
    fi
}

processOutputFile() {
    case "${1}" in
        -*|'')
            echo "ERROR: No FILENAME given after -o or --output-filename." >&2
            exit 1
            ;;
        *)
            ofname="${1}"
            ;;
    esac
}

processSize() {
    if [[ "${1}" == 'auto' ]]
    then
        size='auto'
    elif [[ ${1} =~ ^[0-9]+ ]]
    then
        if (( ${1} >= 1 && ${1} <= 40 ))
        then
            size=${1}
        else
            echo "ERROR: Size must be a NUMBER btw. 1-40." >&2
            exit 1;
        fi
    else
        echo "ERROR: Missing NUMBER or 'auto' after -s or --size." >&2
        exit 1;
    fi
}

if ! command -v pdflatex >/dev/null 2>&1
then
    echo '
Please install pdflatex before using qrcreate.
'
    exit 1
fi

if [[ $# -eq 0 ]]
then
    if [[ -t 0 ]]
    then
        # No parameter is given and no pipes are redirected.
        # Behave as if -h is specified.
        set -- "-h" "$@"
    else
        # No parameter is given but a pipe is redirected.
        # Behave as if -s is specified.
        set -- "-s" "$@"
    fi
fi

while [[ $# -gt 0 ]]; do
    case "${1}" in
        -c|--copyright)
            echoCopyright
            exit 0
            ;;
        -d|--data-str)
            shift
            processDataStr "${1}"
            ;;
        -d=*|--data-str=*)
            processDataStr "${1#*=}"
            ;;
        -h|--help)
            echoUsage
            exit 0
            ;;
        -i|--input-filename)
            shift
            processInputFile "${1}"
            ;;
        -i=*|--input-filename=*)
            processInputFile "${1#*=}"
            ;;
        -l|--link)
            link='link'
            ;;
        -L|--level)
            shift
            processLevel "${1}"
            ;;
        -L=*|--level=*)
            processLevel "${1#*=}"
            ;;
        -n|--nolink)
            link='nolink'
            ;;
        -N|--nruns)
            shift
            processNRuns "${1}"
            ;;
        -N=*|--nruns=*)
            processNRuns "${1#*=}"
            ;;
        -o|--output-filename)
            shift
            processOutputFile "${1}"
            ;;
        -o=*|--output-filename=*)
            processOutputFile "${1#*=}"
            ;;
        -p|--padding)
            pad='padding'
            ;;
        -s|--stdin)
            data="${data}$(cat)"
            ;;
        -S|--size)
            shift
            processSize "${1}"
            ;;
        -S=*|--size=*)
            processSize "${1#*=}"
            ;;
        -t|--tight)
            pad='tight'
            ;;
        -v|--version)
            echoVersion
            exit 0
            ;;
        *)
            echo "ERROR: Unknown option ${1}" >&2
            exit 1
            ;;
    esac
    shift
done

# If -s is NOT specified, but some pipe is redirected, behave as if there was a -s at the end.
if [[ ! -t 0 ]]; then data="${data}$(cat)"; fi

# If data is still empty, give ERROR.
if [[ -z "${data}" ]]; then echo "ERROR: Cannot create the QR code of empty data." >&2; exit 1; fi

if [[ "${size}" == "auto" ]]; then size=""; else size=",version=${size}"; fi

job=${ofname%.pdf}

tmp=$(mktemp)
status=$?
if [ ${status} -ne 0 ]
then
    echo "ERROR: Cannot create a temporary file." >&2
    exit 1
fi

printf '%s' "${data}" > "${tmp}"

for i in {1..${nruns}}
do
if ! pdflatex -jobname="${job}" <<EOF
\documentclass{standalone}
\usepackage{csvsimple}
\usepackage{hyperref}
\usepackage[${link}]{qrcodetikz}
\begin{document}
\csvreader[no head,respect all]{${tmp}}{}{\qrcode[level=${level}${size},${pad}]{\csvcoli}}
\end{document}
EOF
then
    echo "ERROR: pdflatex failed" >&2
    rm -f "${tmp}"
    exit 1
fi
done

rm -f "${job}".aux "${job}".log "${job}".out "${tmp}"
